---
- name: Instalar Apache, MariaDB, PHP y PhpMyAdmin
  zypper:
    name:
      - apache2
      - mariadb
      - php
      - php-mysql
      - apache2-mod_php8
      - phpMyAdmin
    state: present
  register: result_lamp
  until: result_lamp is succeeded
  retries: 3
  delay: 5

- name: Habilitar el modulo PHP en Apache
  command: a2enmod php8
  ignore_errors: yes

- name: Asegurar que MariaDB (MySQL) este iniciada
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Establecer contrasena para el usuario root de MySQL 
  command: >
    mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'mundolibre'; FLUSH PRIVILEGES;"
  ignore_errors: yes

- name: Crear base de datos 'prueba'
  command: mysql -u root -p'mundolibre' -e "CREATE DATABASE IF NOT EXISTS prueba;"
  ignore_errors: yes

- name: Copiar phpMyAdmin al Document Root de Apache
  command: cp -r /usr/share/phpMyAdmin /srv/www/htdocs/
  args:
    creates: /srv/www/htdocs/phpMyAdmin

- name: Copiar archivo de prueba PHP (info.php)
  copy:
    src: info.php
    dest: /srv/www/htdocs/info.php
    mode: '0644'

- name: Asegurar que Apache (Servidor Web) este iniciado y reiniciado
  service:
    name: apache2
    state: restarted
    enabled: yes
